name: Publish to vercel

on:
    push:
        branches: [ "main" ]

jobs:
    publish:
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message, '[publish]')"
        steps:
            - name: publish
              run: curl ${{ secrets.VERCEL_DEPLOY_HOOK }}
